version: '3.7'
services:
  db:
    image: timescale/timescaledb:2.3.0-pg12
    secrets:
      - timescale_historian_root_password
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/timescale_historian_root_password
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - factory-plus
    deploy:
      placement:
        constraints:
          - node.hostname == amrc-factoryP-h
      restart_policy:
        condition: on-failure
        delay: 5s

  postgres_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    command: --auto-discover-databases
    environment:
      - DATA_SOURCE_URI=db?sslmode=disable
      - DATA_SOURCE_USER=postgres_exporter
      - DATA_SOURCE_PASS_FILE=/run/secrets/timescale_historian_exporter_password
    secrets:
       - timescale_historian_exporter_password
    deploy:
      labels:
        - "prometheus-job=timescale-historian"
        - "prometheus-port=9187"
      placement:
        constraints:
          - node.hostname == amrc-factoryP-h
    networks:
       - factory-plus
    depends_on:
      - db
secrets:
  timescale_historian_root_password:
    external: true
  timescale_historian_exporter_password:
    external: true

volumes:
  data:

networks:
  factory-plus:
    external: true
    name: factory-plus
